# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ae157ca077e7b059bb1f461e10a8a1c71b3bb3498031063bed435d8e10eaa03a2b7e278b65c4645b06450b8dfd698a86b944d3fc86cbb55bb34f7594eced1ace

test:
  secret_key_base: e44c4630fa224dc3899f5cb5528920470bb02205e5042b2fbed1b56812015432a7429f00bfaed8a21a380c2534aa2c02c9b93be5595265897f6ead82c43763d8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  AWS_REGION: eu-west-1
  S3_BUCKET_NAME: hedera1
  AWS_ACCESS_KEY_ID: ENV["AWS_ACCESS_KEY_ID"]
  AWS_SECRET_ACCESS_KEY: +xUFkBWNILSuktf2O97f1sqeV6+3QJLnhxqXFcUV
